#pragma once

#include "components/themes/lyra/LyraTheme.h"

namespace VesperMetrics {
constexpr ThemeMetrics values = {
    .batteryWidth = 16,
    .batteryHeight = 12,
    .topPadding = 4,
    .batteryBarHeight = 40,
    .headerHeight = 78,
    .verticalSpacing = 12,
    .previewPadding = 12,
    .previewHeightPercent = 30,
    .contentSidePadding = 16,
    .listRowHeight = 44,
    .listWithSubtitleRowHeight = 62,
    .listRowGap = 2,
    .listRowRadius = 3,
    .listInset = 12,
    .listSidePadding = 12,
    .listSelectionStyle = 0,
    .listScrollWidth = 3,
    .listScrollSide = 0,
    .listTitleBold = false,
    .headerSidePadding = 16,
    .headerUnderlineSize = 1,
    .headerTitleAlign = 0,
    .headerBatterySide = 0,
    .headerBatteryDetached = true,
    .menuRowHeight = 52,
    .menuSpacing = 4,
    .tabSpacing = 6,
    .tabBarHeight = 44,
    .scrollBarWidth = 3,
    .scrollBarRightOffset = 5,
    .homeTopPadding = 52,
    .homeCoverHeight = 190,
    .homeCoverTileHeight = 208,
    .homeRecentBooksCount = 1,
    .homeContinueReadingInMenu = false,
    .homeMenuTopOffset = 10,
    .buttonHintsHeight = 40,
    .sideButtonHintsWidth = 30,
    .progressBarHeight = 12,
    .progressBarMarginTop = 1,
    .statusBarHorizontalMargin = 6,
    .statusBarVerticalMargin = 16,
    .keyboardKeyHeight = 48,
    .keyboardKeySpacing = 2,
    .keyboardCenteredText = true,
    .keyboardVerticalOffset = -6,
    .keyboardTextFieldWidthPercent = 88,
    .keyboardWidthPercent = 94,
    .popupTopOffsetRatio = 0.14f,
    .popupMarginX = 16,
    .popupMarginY = 12,
    .popupFrameThickness = 1,
    .popupCornerRadius = 4,
    .popupTextBold = false,
    .popupTextInverted = false,
    .popupTextBaselineOffsetY = -2,
    .popupProgressBarHeight = 4,
    .popupProgressDrawOutline = true,
    .popupProgressClampPercent = true,
    .popupProgressFillInverted = false,
    .popupProgressOutlineInverted = false,
    .optionPopupItemSpacing = 6,
    .optionPopupInnerPadding = 18,
    .optionPopupSelectionVPadding = 10,
    .optionPopupDialogSideMargin = 18,
    .textFieldHorizontalPadding = 8,
    .textFieldNormalThickness = 1,
    .textFieldCursorThickness = 2,
    .textFieldLineEndOffset = 0,
    .controlRadius = 4,
    .sheetRadius = 4,
    .capsuleRadius = 4,
};
}  // namespace VesperMetrics

class VesperTheme final : public LyraTheme {
 public:
  void drawHeader(const GfxRenderer& renderer, Rect rect, const char* title,
                  const char* subtitle = nullptr) const override;
};
